# Ação do GitHub para gerar um gráfico de contribuições com uma cobra que consome suas contribuições.

name: Gerar Cobra

# Controla quando a ação será executada. Esta ação é executada a cada 6 horas.

on:
  schedule:
    # a cada 6 horas
    - cron: "0 */6 * * *"

# Este comando nos permite executar a ação automaticamente a partir da guia Actions.
  workflow_dispatch:

# A sequência de execuções neste fluxo de trabalho:
jobs:
  # Este fluxo de trabalho contém uma única tarefa chamada "build"
  build:
    # O tipo de executor em que a tarefa será executada
    runs-on: ubuntu-latest

    # As etapas representam uma sequência de tarefas que serão executadas como parte da tarefa
    steps:

    # Verifica o repositório em $GITHUB_WORKSPACE, para que sua tarefa possa acessá-lo
      - uses: actions/checkout@v2.5.0

    # Gera a cobra  
      - uses: Platane/snk@main
        id: snake-gif
        with:
          github_user_name: joaopamarall
          entryPoint: dist/github-contribution-grid-snake.gif
          args: '--output ${{ github.event.inputs.outputs }}'

     # mostra o status da compilação. Torna mais fácil para depurar (se houver algum problema).
      - run: git status

      # Faz o push das alterações
      - name: Push das alterações
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          # o branch de saída que mencionamos acima
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
